Controllers/DipendentiController.cs
using Microsoft.AspNetCore.Mvc;

namespace Edilizia.Controllers
{
    public class DipendentiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }
    }
}

Views/Dipendenti/Add.cshtml
@section Title{
    Aggiungi Dipendenti
}


@section Pretitle{
    <h3>Compila il form per l'aggiunta di nuovi dipendenti</h3>
}


<form>

  
        <label for="fname">Nome:</label>
        <input type="text" id="Nome" name="fname"><br><br>

        <label for="lname">Cognome:</label>
        <input type="text" id="Cognome" ><br><br>

         <label for="fname">Indirizzo:</label>
         <input type="text" id="Indirizzo" ><br><br>

         <label for="fname">Codice Fiscale:</label>
         <input type="text" id="CodFis" ><br><br>

          <label for="fname">Sposato:</label>
           <input type="text" id="Sposato"><br><br>

          <label for="fname">Figli:</label>
            <input type="text" id="Figli"><br><br>

            <label for="fname">Mansione:</label>
            <input type="text" id="Mansione" ><br><br>

    

    <input type="submit" value="Submit">
    
   

</form>

Views/Dipendenti/Index.cshtml
@section Title {
    Dipendenti
}

@section PreTitle {
    <h3>Lista Dipendenti</h3>
}

<table border="1">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Indirizzo</th>
            <th>Codice Fiscale</th>
            <th>Sposato</th>
            <th>Figli</th>
            <th>Mansione</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Dato 1</td>
            <td>Dato 2</td>
            <td>Dato 3</td>
            <td>Dato 4</td>
            <td>Dato 5</td>
            <td>Dato 6</td>
            <td>Dato 7</td>
        </tr>
    </tbody>
</table>

Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@*  il layout ci serve a definire le parti in comune con tutte le views *@

@*   serve per dare la possibilita al cotnrollor e alla action di no nessere
 cose html ,ma di prendere la funzionalità cs,
 le centralizzeremo dentro un file speciale chiamato _ViewImports *@
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers 

<!DOCTYPE html>
<html lang="" it"">
<head>
    <meta charset="" UTF-8"">
    <meta name="" viewport"" content="" width=device-width, initial-scale=1.0"">
 @*    questo è un secondo placeholder che utilizziamo per rendere dinamico
    una seconda parte della pagina. Visto che RenderBody possiamo utilizzarlo solo uan volta
    non passo il secondo argomento a false, quindi è obligatorio *@
    <title>@RenderSection("Title")</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>

    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    @* placegolder personalizzato *@
    @RenderSection("PreTitle", false)

    <ul>
        <li><a asp-controller="Dipendenti" asp-action="Index">Lista Dipendenti</a></li>
        <li><a asp-controller="Dipendenti" asp-action="Add">Aggiungi Dipendenti</a></li>
    </ul>

   @*  // è un placeholder che utiliziam per dire, che altre views finirannoli dentro *@
   <h1>Primo sito MVC</h1>
    @RenderBody()


    @* Creiamo un placeholder per gli script *@
  @RenderSection("Scripts", false)
</body>
</html>